In [21]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np


In [22]:
# Definir la red neuronal
class BinaryClassifier(nn.Module):
    def __init__(self):
        super(BinaryClassifier, self).__init__()
        self.fc1 = nn.Linear(8, 16)
        self.fc2 = nn.Linear(16, 32)
        self.fc3 = nn.Linear(32, 1)
    
    def forward(self, x):
        x = torch.sigmoid(self.fc1(x))
        x = torch.sigmoid(self.fc2(x))
        x = torch.sigmoid(self.fc3(x))
        return x

In [23]:
# Generar todos los números de 8 bits
numbers = np.arange(256, dtype=np.uint8)
binary_numbers = np.unpackbits(numbers.reshape(-1, 1), axis=1)

# Calcular la cantidad de bits de 1 en cada número
num_ones = np.sum(binary_numbers, axis=1)

# Etiquetar los números que cumplen con la condición
labels = np.where((num_ones > 4) | ((num_ones == 4) & (binary_numbers[:, 0] == 0)), 1, 0)
print("Valores:")
print(binary_values)
print("Etiquetas:")
print(labels)

# Convertir los datos a tensores de PyTorch
X = torch.tensor(binary_numbers, dtype=torch.float32)
y = torch.tensor(labels.reshape(-1, 1), dtype=torch.float32)


Valores:
[[0 0 1 0 1 0 1 1]
 [1 1 0 1 0 0 0 1]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 1 1 1]]
Etiquetas:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 1 0 0 0 0 0
 0 0 1 0 0 0 1 0 1 1 1 0 0 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1 0 0
 0 1 0 1 1 1 0 0 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 0 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 1 0 0 0 1 0 1 1 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 1 0 0 0 1 0 1 1 1 0
 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 1 1 0 0 0 1 0 1 1 1 0 1 1 1 1 1
 1 1 0 0 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [24]:
# Inicializar la red neuronal, la función de pérdida y el optimizador
model = BinaryClassifier()
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

In [25]:
# Entrenar la red neuronal
num_epochs = 10000
for epoch in range(num_epochs):
    # Paso de adelante (forward)
    y_pred = model(X)
    
    # Calcular la pérdida
    loss = criterion(y_pred, y)
    
    # Paso de atrás (backward) y actualización de los pesos
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    # Imprimir la pérdida en cada 1000 épocas
    if (epoch + 1) % 1000 == 0:
        print(f'Época [{epoch + 1}/{num_epochs}], Pérdida: {loss.item():.4f}')

Época [1000/10000], Pérdida: 0.0001
Época [2000/10000], Pérdida: 0.0000
Época [3000/10000], Pérdida: 0.0000
Época [4000/10000], Pérdida: 0.0000
Época [5000/10000], Pérdida: 0.0000
Época [6000/10000], Pérdida: 0.0000
Época [7000/10000], Pérdida: 0.0000
Época [8000/10000], Pérdida: 0.0000
Época [9000/10000], Pérdida: 0.0000
Época [10000/10000], Pérdida: 0.0000


In [26]:
# Evaluar la precisión del modelo en el conjunto de datos completo
with torch.no_grad():
    y_pred = model(X)
    y_pred = torch.round(y_pred)
    accuracy = (y_pred == y).sum().item() / y.size(0)
    print(f'Precisión en el conjunto de datos completo: {accuracy:.4f}')

Precisión en el conjunto de datos completo: 1.0000


In [27]:
values = np.array([0b00101011, 0b11010001, 0b11111111, 0b00000111], dtype=np.uint8)
binary_values = np.unpackbits(values.reshape(-1, 1), axis=1)
X_pred = torch.tensor(binary_values, dtype=torch.float32)
with torch.no_grad():
    y_pred = model(X_pred)
    y_pred = torch.round(y_pred)
    print("Valores de entrada:")
    print(binary_values)
    print("Etiquetas predichas:")
    print(y_pred.numpy().astype(int).flatten())

Valores de entrada:
[[0 0 1 0 1 0 1 1]
 [1 1 0 1 0 0 0 1]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 1 1 1]]
Etiquetas predichas:
[1 0 1 0]
